title: Blue-Blazed Trail Running Series
description: A trail running series on Connecticut's Blue-Blazed Hiking Trails
baseurl: ""
url: https://blueblazedtrailrunningseries.org
webmaster_verifications:
  google: fYpDKFmxkqLqky-jk4rYDMKlxRmbAmQp9VjI9zx9x-s
logo: /images/blueblazedlogo.jpg
facebook:
  publisher: https://www.facebook.com/BBTRAILRS/
timezone: America/New_York
markdown:  kramdown
exclude:   
  - README.md
  - .git
  - .gitignore
  - .gitattributes  
  - .jekyll-cache
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docs/
plugins:
  - jekyll-sitemap
collections:
  races:
    layout: race
    output: true
  results:
    output: true
  api:
    output: true
year: 2026
